### ISSUE TITLE
Add ESLint rule to prevent HTML comments inside Vue templates

### ISSUE THREAD

**Issue by Kalissaac** [ocf/ocfstatic#245]
As seen in #210 adding HTML comments inside Vue templates causes hydration to fail, which breaks almost all interactive functionality of the site.

Instead of using HTML comments (`<!-- comment -->`), we could instead use JS template comments (`{{ comment }}`) ~~which have the additional benefit of being stripped out of the final build~~.

**Comment by Kalissaac** [comment]
Additionally, having some kind of automatic hydration check every time we run a build would be nice, not sure if Gridsome supports that.

**Comment by ethanwu10** [comment]
I haven't had too much time to debug what exactly happens, but HTML `<!-- -->` comments *do* get stripped out of the final build (at least for SSR). Also, from a cursory glance at the [ASTs](https://astexplorer.net/#/gist/91b714ad8e045d37054bd1c31cd5edc8/cbb232fdb9d70774577132185b5b777ba7c7e7cd) produced by the eslint parser, detecting the location of a comment is quite annoying since they are at the root of the `<template>` and not the node they're contained in. Flat-out banning HTML comments would be easier, but we need to check that JS comments don't break it either.

**Comment by Kalissaac** [comment]
Oh ok that's good to know about HTML comments. I just tested it and hydration worked fine for me with JS comments.

As for the hydration test, I didn't really take that into account, it definitely seems like something that would require a lot more fine tuning to get right.
